version: 2
jobs:
    build:
        docker:
            - image: crazyhugsy/gef:dev
        working_directory: ~/repo
        steps:
            - checkout
            - run: python3 -m pylint -E gef.py
            - run: make lint
            - run: make test
